const calcData = [
    {
      id: 1,
      title: 'AC',
      bg: 'white',
      color: 'black',
      width: 80,
      height: 80,
    },
    {
      id: 2,
      title: '±',
      bg: 'white',
      color: 'black',
      width: 80,
      height: 80,
      type: 'operation',
      operation: 'negative',
    },
    {
      id: 3,
      title: '%',
      bg: 'white',
      color: 'black',
      width: 80,
      height: 80,
      type: 'operation',
      operation: 'mod',
    },
    {
      id: 4,
      title: '÷',
      bg: 'orange',
      color: 'white',
      width: 80,
      height: 80,
      type: 'operation',
      operation: 'divide',
    },
    {
      id: 5,
      title: '1',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 6,
      title: '2',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 7,
      title: '3',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 8,
      title: 'x',
      bg: 'orange',
      color: 'white',
      width: 80,
      height: 80,
      type: 'operation',
      operation: 'mul',
    },
    {
      id: 9,
      title: '4',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 10,
      title: '5',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 11,
      title: '6',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 12,
      title: '-',
      bg: 'orange',
      color: 'white',
      width: 80,
      height: 80,
      type: 'operation',
      operation: 'minus',
    },
    {
      id: 13,
      title: '7',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 14,
      title: '8',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 15,
      title: '9',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 16,
      title: '+',
      bg: 'orange',
      color: 'white',
      width: 80,
      height: 80,
      type: 'operation',
      operation: 'sum',
    },
    {
      id: 17,
      title: '0',
      bg: '#555555',
      color: 'white',
      width: 165,
      height: 80,
      type: 'num',
    },
    {
      id: 17,
      title: '.',
      bg: '#555555',
      color: 'white',
      width: 80,
      height: 80,
      type: 'num',
    },
    {
      id: 17,
      title: '=',
      bg: 'orange',
      color: 'white',
      width: 80,
      height: 80,
      type: 'operation',
      operation: 'equal to',
    },
  ];

export default calcData